/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_klass_TestDll */

#ifndef _Included_jni_klass_TestDll
#define _Included_jni_klass_TestDll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_klass_TestDll
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_klass_TestDll_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     jni_klass_TestDll
 * Method:    sayHello1
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jni_klass_TestDll_sayHello1
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jni_klass_TestDll
 * Method:    copyFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jni_klass_TestDll_copyFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
